# Generated by Django 3.1.2 on 2020-10-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='message',
            field=models.CharField(max_length=500),
        ),
    ]
